_target_: diffusion_policy.policy.diffusion_unet_hybrid_image_policy.DiffusionUnetHybridImagePolicy
shape_meta: ${task.shape_meta}
horizon: ${horizon}
n_action_steps: ${n_action_steps}
n_obs_steps: ${n_obs_steps}
num_inference_steps: 100
obs_as_global_cond: ${obs_as_global_cond}

# UNet architecture details
kernel_size: 5
n_groups: 8
down_dims: [512, 1024, 2048]
diffusion_step_embed_dim: 128
obs_encoder_group_norm: true
cond_predict_scale: true

# Image processing settings
crop_shape: [84, 84]
eval_fixed_crop: true

# Denoising noise scheduler
noise_scheduler:
  _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
  num_train_timesteps: 100
  beta_schedule: 'squaredcos_cap_v2'
  beta_start: 0.0001
  beta_end: 0.02
  clip_sample: true
  prediction_type: 'epsilon'
  variance_type: 'fixed_small'

